#!/usr/bin/env python3
"""
Regenerate ATARILIB/c2p_palette_opt_weights.inc and c2p_palette_opt_subset.inc
from tools/palette-opt (TEMPERAT.PAL in playpal.c, spread subset).

Run from repository root (TIBERIANDAWN):
  python3 tools/palette-opt/gen_c2p_palette_opt_weights_inc.py

Requires: tools/palette-opt built (make -C tools/palette-opt).
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def parse_subset(stderr: str) -> list[int]:
	for line in stderr.splitlines():
		m = re.search(r"(?:spread|opt) subset \(\d+\):\s*(.*)", line)
		if m:
			nums = [int(x) for x in re.findall(r"\d+", m.group(1))]
			if len(nums) != 16:
				raise ValueError(f"expected 16 subset indices, got {len(nums)}: {nums}")
			return nums
	raise ValueError("subset line not found in palette-opt stderr")


def parse_weights(stdout: str) -> list[list[int]]:
	rows: list[list[int]] = []
	for line in stdout.strip().splitlines():
		head = line.split("//", 1)[0]
		nums = [int(x) for x in re.findall(r"\d+", head)]
		if len(nums) != 16 or sum(nums) != 16:
			raise ValueError(f"bad weight row: {line!r}")
		rows.append(nums)
	if len(rows) != 256:
		raise ValueError(f"expected 256 weight rows, got {len(rows)}")
	return rows


def write_subset_inc(path: Path, subset: list[int]) -> None:
	inner = ", ".join(str(n) for n in subset)
	text = "\n".join(
		[
			"/*",
			" * Auto-generated by tools/palette-opt/gen_c2p_palette_opt_weights_inc.py",
			" * Palette indices for pens 0..15 (spread subset, TEMPERAT.PAL).",
			" */",
			"",
			f"static const uint8_t kC2PPaletteOptSubset[16] = {{ {inner} }};",
			"",
		]
	)
	path.write_text(text)


def write_weights_inc(path: Path, subset: list[int], rows: list[list[int]]) -> None:
	subset_s = ", ".join(str(n) for n in subset)
	out: list[str] = [
		"/*",
		" * Auto-generated by tools/palette-opt/gen_c2p_palette_opt_weights_inc.py",
		f" * TEMPERAT.PAL in playpal.c; spread subset: {subset_s}.",
		" */",
		"",
		"static const uint8_t kC2PPaletteOptWeight[256][16] = {",
	]
	for i, nums in enumerate(rows):
		inner = ", ".join(str(n) for n in nums)
		comma = "," if i < 255 else ""
		out.append(f"\t{{ {inner} }}{comma}")
	out.append("};")
	out.append("")
	path.write_text("\n".join(out))


def main() -> int:
	td = Path(__file__).resolve().parents[2]
	opt_dir = td / "tools" / "palette-opt"
	po = opt_dir / "palette-opt"
	if not po.is_file():
		print("error: build palette-opt first: make -C tools/palette-opt", file=sys.stderr)
		return 1

	proc = subprocess.run(
		[str(po), "--sa-iter=0"],
		cwd=str(opt_dir),
		check=True,
		capture_output=True,
		text=True,
	)
	subset = parse_subset(proc.stderr)
	rows = parse_weights(proc.stdout)

	atari = td / "ATARILIB"
	write_subset_inc(atari / "c2p_palette_opt_subset.inc", subset)
	write_weights_inc(atari / "c2p_palette_opt_weights.inc", subset, rows)
	print("Wrote", (atari / "c2p_palette_opt_subset.inc").relative_to(td))
	print("Wrote", (atari / "c2p_palette_opt_weights.inc").relative_to(td))
	print("subset:", subset)
	return 0


if __name__ == "__main__":
	sys.exit(main())
