#!/usr/bin/env python3
"""
Regenerate ATARILIB/c2p_palette_opt_weights.inc from tools/palette-opt.

Run from repository root (TIBERIANDAWN):
  python3 tools/palette-opt/gen_c2p_palette_opt_weights_inc.py

Requires: tools/palette-opt built (make -C tools/palette-opt).
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def main() -> int:
	td = Path(__file__).resolve().parents[2]  # TIBERIANDAWN (…/tools/palette-opt/this.py)
	opt_dir = td / "tools" / "palette-opt"
	po = opt_dir / "palette-opt"
	if not po.is_file():
		print("error: build palette-opt first: make -C tools/palette-opt", file=sys.stderr)
		return 1

	proc = subprocess.run(
		[str(po), "0", "256"],
		cwd=str(opt_dir),
		check=True,
		capture_output=True,
		text=True,
	)
	lines = proc.stdout.strip().splitlines()
	rows: list[list[int]] = []
	for line in lines:
		head = line.split("//", 1)[0]
		nums = [int(x) for x in re.findall(r"\d+", head)]
		if len(nums) != 16 or sum(nums) != 16:
			print("bad line:", line, file=sys.stderr)
			return 1
		rows.append(nums)
	if len(rows) != 256:
		print("error: expected 256 rows, got", len(rows), file=sys.stderr)
		return 1

	outp = td / "ATARILIB" / "c2p_palette_opt_weights.inc"
	out: list[str] = []
	out.append("/*")
	out.append(" * Auto-generated by tools/palette-opt/gen_c2p_palette_opt_weights_inc.py")
	out.append(" * (TEMPERAT.PAL in playpal.c, subset indices 0..15).")
	out.append(" */")
	out.append("")
	out.append("static const uint8_t kC2PPaletteOptWeight[256][16] = {")
	for i, nums in enumerate(rows):
		inner = ", ".join(str(n) for n in nums)
		comma = "," if i < 255 else ""
		out.append(f"\t{{ {inner} }}{comma}")
	out.append("};")
	out.append("")
	outp.write_text("\n".join(out))
	print("Wrote", outp.relative_to(td))
	return 0


if __name__ == "__main__":
	sys.exit(main())
