"""Movep-ready packing and C include emission for YM digi LUTs."""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Sequence, Tuple

from ym_optimal import LutEntry

VolABC = Tuple[int, int, int]


def entry_size(channels: int) -> int:
    return {1: 2, 2: 4, 3: 8}[channels]


def pack_u16(vols: VolABC) -> int:
    """BE word 0x08va — in m68k memory: 08 va for movep.w."""
    a, _, _ = vols
    return (0x08 << 8) | (a & 0x0F)


def pack_u32_ab(vols: VolABC) -> int:
    """BE long 0x08va09vb — in m68k memory: 08 va 09 vb for movep.l."""
    a, b, _ = vols
    return (0x08 << 24) | ((a & 0x0F) << 16) | (0x09 << 8) | (b & 0x0F)


def pack_u16_c(vols: VolABC) -> int:
    """BE word 0x0Avc — in m68k memory: 0a vc for movep.w."""
    _, _, c = vols
    return (0x0A << 8) | (c & 0x0F)


def _fmt_rows(values: Sequence[str], per_row: int) -> str:
    lines = []
    for i in range(0, len(values), per_row):
        chunk = values[i : i + per_row]
        lines.append("\t" + ", ".join(chunk) + ",")
    return "\n".join(lines)


def emit_lut_inc(
    entries: Sequence[LutEntry],
    channels: int,
    prefix: str,
) -> str:
    n = len(entries)
    es = entry_size(channels)
    header = [
        f"/* Auto-generated by ym_lut_gen.py — do not edit.",
        f" * {prefix}: {n} entries x {es} bytes, {channels}-channel movep LUT.",
        f" * Integer constants are big-endian (m68k): high byte = YM register,",
        f" * next = volume nibble — matching in-memory order for movep.",
        f" */",
        "",
    ]
    if channels == 1:
        vals = [f"0x{pack_u16(v):04X}" for v, _ in entries]
        body = (
            f"static uint16_t const {prefix}_lut[{n}] = {{\n"
            + _fmt_rows(vals, 8)
            + "\n};\n"
        )
    elif channels == 2:
        vals = [f"0x{pack_u32_ab(v):08X}u" for v, _ in entries]
        body = (
            f"static uint32_t const {prefix}_lut[{n}] = {{\n"
            + _fmt_rows(vals, 4)
            + "\n};\n"
        )
    else:
        lines = [
            f"typedef struct {prefix}_ym_slot {{",
            "\tuint32_t ab; /* 0x08va09vb */",
            "\tuint16_t c;  /* 0x0Avc */",
            "\tuint16_t pad;",
            f"}} {prefix}_ym_slot;",
            "",
            f"static {prefix}_ym_slot const {prefix}_lut[{n}] = {{",
        ]
        for vols, _ in entries:
            ab = pack_u32_ab(vols)
            c = pack_u16_c(vols)
            lines.append(f"\t{{ 0x{ab:08X}u, 0x{c:04X}, 0 }},")
        lines.append("};")
        lines.append("")
        body = "\n".join(lines) + "\n"

    return "\n".join(header) + body


def emit_remap_inc(remap: Sequence[int], prefix: str) -> str:
    vals = [f"0x{i:02X}" for i in remap]
    return (
        f"/* Auto-generated by ym_lut_gen.py — 8-bit sample -> LUT byte offset */\n"
        f"static uint8_t const {prefix}_remap[256] = {{\n"
        + _fmt_rows(vals, 16)
        + "\n};\n"
    )


def emit_meta_inc(
    prefix: str,
    *,
    model: str,
    channels: int,
    bits: int,
    pcm: str,
    amin: float,
    amax: float,
    stats: dict,
) -> str:
    n = stats["n"]
    es = entry_size(channels)
    lines = [
        f"/* Auto-generated by ym_lut_gen.py",
        f" * model={model} channels={channels} bits={bits} pcm={pcm}",
        f" * amin={amin:.4f} amax={amax:.4f}",
        f" * distinct_full={stats.get('distinct_full')} distinct={stats.get('distinct')}",
        f" * rmse={stats['rmse']:.4f} ({100.0 * stats['rmse_fs']:.4f}% FS)",
        f" * mode={stats.get('mode', 'thin')}",
        f" * thinned={stats.get('thinned')}",
        f" * big-endian m68k; grid index byte offset = sample & 0xFC (entry_size={es})",
        f" */",
        f"#define {prefix.upper()}_CHANNELS {channels}",
        f"#define {prefix.upper()}_BITS {bits}",
        f"#define {prefix.upper()}_N {n}",
        f"#define {prefix.upper()}_ENTRY_SIZE {es}",
        f'#define {prefix.upper()}_MODEL "{model}"',
        f'#define {prefix.upper()}_PCM "{pcm}"',
        "",
    ]
    return "\n".join(lines)


def emit_lut_asm(entries: Sequence[LutEntry], channels: int) -> str:
    """GAS .long lines for embedding in audio_timer_dac_ym.S (2-ch only)."""
    if channels != 2:
        raise ValueError("emit_lut_asm supports 2-channel LUTs only")
    lines = [
        "\t/* Auto-generated by ym_lut_gen.py --mode grid — 64-bin YM lut (pcm from generator) */",
    ]
    vals = [f"0x{pack_u32_ab(v):08X}" for v, _ in entries]
    for i in range(0, len(vals), 4):
        chunk = vals[i : i + 4]
        lines.append("\t.long\t" + ", ".join(chunk))
    lines.append("")
    return "\n".join(lines)


def write_outputs(
    out_dir: Path,
    prefix: str,
    entries: Sequence[LutEntry],
    remap: Optional[Sequence[int]],
    channels: int,
    *,
    write_remap: bool = True,
    write_asm: bool = False,
    **meta,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{prefix}_lut.inc").write_text(
        emit_lut_inc(entries, channels, prefix), encoding="utf-8"
    )
    if write_remap and remap is not None:
        (out_dir / f"{prefix}_remap.inc").write_text(
            emit_remap_inc(remap, prefix), encoding="utf-8"
        )
    (out_dir / f"{prefix}_meta.inc").write_text(
        emit_meta_inc(prefix, channels=channels, **meta), encoding="utf-8"
    )
    if write_asm:
        (out_dir / f"{prefix}_lut.S.inc").write_text(
            emit_lut_asm(entries, channels), encoding="utf-8"
        )
